version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - ^examples/
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
