name: Quay API Verified Nightly

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggers

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: ${{ secrets.QUAY_TOKEN }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Download dependencies
      run: go mod download

    - name: Build binary
      run: go build -o bin/go-quay .

    - name: Run integration tests script
      run: ./scripts/integration-test.sh
      env:
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
        QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE || 'go-quay-test' }}
        
  api-coverage-report:
    name: API Coverage Report
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go  
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Generate API coverage report
      run: ./scripts/generate-api-coverage-report.sh

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: api-coverage-report
        path: api-coverage-report.md

  benchmark-tests:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Run benchmarks
      run: |
        echo "Running performance benchmarks..."
        go test -bench=. -benchmem ./... > benchmark-results.txt 2>&1 || true
        echo "Benchmark results:"
        cat benchmark-results.txt

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark-results.txt